main:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "How we work"
    url: "/#"
    weight: 2

  - name: "Our team"
    url: "/#"
    weight: 3

  - name: "Pricing"
    url: "/#"
    weight: 4

  - name: "Blog"
    url: "/blog"
    weight: 5

buttons:
  - name: "Book a call"
    url: "/#"
    weight: 5

footer:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "How we work"
    url: "/#"
    weight: 2

  - name: "Our team"
    url: "/#"
    weight: 3

  - name: "Pricing"
    url: "/#"
    weight: 4

  - name: "Blog"
    url: "/blog"
    weight: 5
