main:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Research"
    url: "/#cta"
    weight: 2

  - name: "Publications"
    url: "/#services"
    weight: 3

  - name: "Products"
    url: "/#"
    weight: 4

  - name: "Services"
    url: "/#"
    weight: 5

  - name: "Teams"
    url: "/#"
    weight: 6

  - name: "Blog"
    url: "/blog"
    weight: 7

buttons:
  - name: "Contact"
    url: "/#"
    weight: 8

footer:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Research"
    url: "/#"
    weight: 2

  - name: "Publications"
    url: "/#"
    weight: 3

  - name: "Products"
    url: "/#"
    weight: 4

  - name: "Services"
    url: "/#"
    weight: 5

  - name: "Teams"
    url: "/#"
    weight: 6

  - name: "Blog"
    url: "/blog"
    weight: 7
