baseURL: "https://www.njuti.github.io"
theme: "up-business-theme"
languageCode: "en-us"

title: "Threat Intelligence Group"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Threat Intelligence Group"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
    - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "stly@nju.edu.cn"

  copyright: "NJU TIG All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#"
      weight: 1

    - name: "Research"
      url: "/research"
      weight: 2

    - name: "Publication"
      url: "/publication"
      weight: 3

    - name: "Tools"
      url: "/tools"
      weight: 5

    - name: "Teams"
      url: "/teams"
      weight: 6

    - name: "Blog"
      url: "/blog"
      weight: 7

  buttons:
    - name: "Contact"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#"
      weight: 1

    - name: "Research"
      url: "/research"
      weight: 2

    - name: "Publication"
      url: "/publication"
      weight: 3

    - name: "Tools"
      url: "/tools"
      weight: 5

    - name: "Teams"
      url: "/teams"
      weight: 6

    - name: "Blog"
      url: "/blog"
      weight: 7

taxonomies:
  series: "series"
  tags: "tags"
